# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='publications',
            new_name='publication',
        ),
        migrations.AddField(
            model_name='snp',
            name='name',
            field=models.CharField(default='rs?', max_length=255),
        ),
    ]
