# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0002_auto_20170302_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='phenotype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gwasdb.Phenotype'),
        ),
        migrations.AlterField(
            model_name='snp',
            name='gene',
            field=models.ManyToManyField(blank=True, to='gwasdb.Gene'),
        ),
    ]
