# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-18 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0004_remove_snp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='snp',
        ),
        migrations.RemoveField(
            model_name='association',
            name='study',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='genotype',
        ),
        migrations.DeleteModel(
            name='Association',
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
        migrations.DeleteModel(
            name='SNP',
        ),
    ]
