# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-23 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0005_auto_20170618_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='n_hits_bonf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='n_hits_perm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
