# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0006_auto_20170623_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='n_hits_thr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
