# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-27 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0007_study_n_hits_thr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='easygwas_link',
        ),
    ]
