# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-28 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0008_remove_study_easygwas_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='number_countries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='number_samples',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
