# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0009_auto_20170628_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='n_hits_fdr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
