# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-08-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0010_study_n_hits_fdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='bh_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='bonferroni_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='permutation_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
