# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-08-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0011_auto_20170809_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='update_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
