# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-09-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0013_study_n_hits_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='publication_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='publication_pmcid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='publication_pmid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
