# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-09-14 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0014_auto_20170906_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenotype',
            name='trait_ontology_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='phenotype',
            name='trait_ontology_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='phenotype',
            name='trait_ontology_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
