# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-09-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0015_auto_20170914_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotype',
            name='trait_ontology_description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
