# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwasdb', '0016_auto_20170914_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenotype',
            name='study_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
