# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-02-27 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maf', models.FloatField()),
                ('pvalue', models.FloatField()),
                ('beta', models.FloatField(blank=True, null=True)),
                ('odds_ratio', models.FloatField(blank=True, null=True)),
                ('confidence_interval', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chromosome', models.IntegerField()),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('arapheno_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.IntegerField()),
                ('position', models.IntegerField()),
                ('annotation', models.CharField(max_length=255)),
                ('gene', models.ManyToManyField(to='gwasdb.Gene')),
                ('genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwasdb.Genotype')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transformation', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('publications', models.URLField(blank=True, null=True)),
                ('easygwas_link', models.URLField(blank=True, null=True)),
                ('genotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwasdb.Genotype')),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='snp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwasdb.SNP'),
        ),
        migrations.AddField(
            model_name='association',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwasdb.Study'),
        ),
    ]
