version: '3'
services:
  backend:
    image: "docker.sci.gmi.oeaw.ac.at/nordborg/aragwas:testing"
    ports:
     - "8000:8000"
    entrypoint:
      - /srv/web/wait-for-it.sh
      - elasticsearch1:9200
      - --
      - sh
      - /srv/web/web-entrypoint.sh
    environment:
      - ES_HOST=http://elastic:changeme@elasticsearch1:9200
      - ARAGWAS_HDF5_FILE_PATH=/opt/aragwas_data
    networks:
      - aragwas
    depends_on:
      - "amqp1"
      - "elasticsearch1"
    volumes:
      - backend:/opt/aragwas_data

  amqp1:
    image: "rabbitmq:3-management"
    hostname: "amqp1"
    container_name: "amqp1"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - aragwas

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch1
    environment:
      - cluster.name=aragwas
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
      - aragwas

volumes:
  esdata1:
    driver: local
  backend:
    driver: local

networks:
  esnet:
  aragwas:
