version: '3'
services:
  backend:
    image: "docker.artifactory.imp.ac.at/the1001genomes/aragwas:latest"
    ports:
     - "8000:8000"
    entrypoint:
      - /srv/web/wait-for-it.sh
      - elasticsearch1:9200
      - --
      - sh
      - /srv/web/web-entrypoint.sh
      - manage.py
    environment:
      - ES_HOST=http://elastic:changeme@elasticsearch1:9200
      - ARAGWAS_HDF5_FILE_PATH=/opt/aragwas_data
      - DATACITE_USERNAME=${DATACITE_USERNAME}
      - DATACITE_PASSWORD=${DATACITE_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - DJANGO_SETTINGS_MODULE=aragwas.settings.prod
    networks:
      - aragwas
    depends_on:
      - "amqp1"
      - "elasticsearch1"
    volumes:
      - /mnt/aragwas_data:/opt/aragwas_data
      - /usr/share/nginx/html/static:/usr/share/nginx/html/static
    restart: unless-stopped

  amqp1:
    image: "rabbitmq:3.6.11-management"
    hostname: "amqp1"
    container_name: "amqp1"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - aragwas
    restart: unless-stopped

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch1
    environment:
      - cluster.name=aragwas
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8G -Xmx8G"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 8g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
      - aragwas
    restart: unless-stopped

    # Celery worker
  worker:
    image: "docker.artifactory.imp.ac.at/the1001genomes/aragwas:latest"
    entrypoint:
      - /srv/web/wait-for-it.sh
      - elasticsearch1:9200
      - --
      - sh
      - /srv/web/worker-entrypoint.sh
    environment:
      - ES_HOST=http://elastic:changeme@elasticsearch1:9200
      - ARAGWAS_HDF5_FILE_PATH=/opt/aragwas_data
      - DATACITE_USERNAME=${DATACITE_USERNAME}
      - DATACITE_PASSWORD=${DATACITE_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - DJANGO_SETTINGS_MODULE=aragwas.settings.prod
    networks:
      - aragwas
    depends_on:
      - "amqp1"
      - "elasticsearch1"
    volumes:
      - /mnt/aragwas_data:/opt/aragwas_data
      - /usr/share/nginx/html/static:/usr/share/nginx/html/static
    restart: unless-stopped

volumes:
  esdata1:
    driver: local

networks:
  esnet:
  aragwas:
